SRC/BOOK_STORE/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf.urls.static import static
from BOOK_STORE import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^jet/', include('jet.urls', 'jet')),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('book.urls')),
    path('', include('coupon.urls')),
    path('', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SRC/book/urls.py
from django.urls import path
from book.views import AllBooksView, BookDetailView, CategoryBooksPageView, search_bar, \
    BookCreationView, CategoryCreationView, StoreroomView, BookEditView, BookDeleteView

urlpatterns = [
    path('search/', search_bar, name='search'),
    path('books', AllBooksView.as_view(), name='books'),
    path('book_details/<slug>', BookDetailView.as_view(), name='book_detail'),
    path('category_books/<slug>', CategoryBooksPageView.as_view(), name='category_books'),
    path('staff/add_book/', BookCreationView.as_view(), name='staff_add_book'),
    path('staff/add_category/', CategoryCreationView.as_view(), name='staff_add_category'),
    path('staff/storeroom/', StoreroomView.as_view(), name='storeroom'),
    path('staff/book/edit/<slug>', BookEditView.as_view(), name='book_edit'),
    path('staff/book/delete/<slug>', BookDeleteView.as_view(), name='book_delete'),
]

SRC/cart/models.py
from django.db import models
from django.urls import reverse


class Cart(models.Model):
    """
    سبد خرید
    """

    class Meta:
        ordering = ('id',)
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبدهای خرید'

    user = models.ForeignKey('account.CustomUser', on_delete=models.CASCADE, verbose_name='کاربر')
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد سبد')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی سبد')

    def __str__(self):
        return f'{self.id}'

    def get_absolute_url(self):
        return reverse('cart', kwargs={id: self.id})


class CartItems(models.Model):
    """
    یک سفارش شامل یک عنوان کتاب با هر تعداد دلخواه و فقط در یک سبد خرید
    """

    ORDER_STATUS = [
        ('F', 'پرداخت و تمام شده'),
        ('U', 'موجود در لیست خرید بعدی'),
        ('O', 'موجود در سبد خرید'),
    ]

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'

    book = models.ForeignKey('book.Book', on_delete=models.CASCADE, verbose_name='کتاب')
    ordered = models.CharField(max_length=4, choices=ORDER_STATUS, default='U', verbose_name='وضعیت سفارش')
    quantity = models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name='سبد')

    @property
    def total_price(self):
        """
        :return: قیمت کل یک سفارش برابر با قیمت کتاب بعد از تخفیف ضرب در تعداد انتخاب شده.
        """

        return self.book.total_price * self.quantity

    def __str__(self):
        return f'{self.id}'

    def get_absolute_url(self):
        return reverse('cart_item_detail', kwargs={id: self.id})


class FinalizedOrders(models.Model):
    """
    یک فاکتور خرید شامل تعدادی از سفارش ها ی یک سبد خرید و یک آدرس از کاربر برای انتقال به درگاه پرداخت
    """

    class Meta:
        verbose_name = 'فاکتورخرید'
        verbose_name_plural = 'فاکتورهای خرید'

    shipping_address = models.ForeignKey('account.ShippingAddress', on_delete=models.CASCADE, verbose_name='ادرس تحویل')
    discount = models.IntegerField(default='0', verbose_name='تخفیف')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name='سبد')
    item = models.ManyToManyField(CartItems, verbose_name='سفارشات')
    price = models.IntegerField(default=0, verbose_name='هزینه')
    created = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد فاکتور')
    payment = models.BooleanField(default=False, verbose_name='وضعیت پرداخت')

    def __str__(self):
        return f'{self.id}'

    @property
    def factor_total_price(self):
        """
        :return: قیمت کل یک فاکتور برابر: قیمت کل منهای تخفیف اعمال شده روی سبد خرید
        """

        total_price = (self.price * (100 - int(self.discount))) / 100
        return total_price

SRC/templates/staff/customers.html
{% extends 'staff/staff.html' %}
{% load static %}
{% block stylesheet %}

    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
    <link rel="stylesheet" href="{% static 'css/storeroom.css' %}">
{% endblock %}
{% block title %}
    مشتریان
{% endblock %}
{% block storeroom %}
    <h2 class="card card-body text-center">مشتریان</h2>
    <div class="container">
        <div class="container mt-3">
            <div class="card card-body storeroom">
                <table class="table table-hover text-right">
                    <thead>
                    <tr>

                        <th scope="col">نام</th>
                        <th scope="col">نام خانوادگی</th>
                        <th scope="col">کدملی</th>
                        <th scope="col">ایمیل</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in customers %}
                        <tr>
                            <td class="editable">{{ customer.first_name }}</td>
                            <td class="editable" >{{ customer.last_name }}</td>
                            <td class="editable" >{{ customer.national_code }}</td>
                            <td class="editable" >{{ customer.email }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock storeroom %}

SRC/templates/staff/factors.html
{% extends 'staff/staff.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
    <link rel="stylesheet" href="{% static 'css/storeroom.css' %}">
{% endblock %}
{% block title %}
    مشتریان
{% endblock %}
{% block storeroom %}
    <h2 class="card card-body text-center">مشتریان</h2>
    <div class="container card card-body storeroom">
        <table class="table table-hover text-right">
            <thead>
            <tr>
                <th scope="col">آدرس</th>
                <th scope="col">تخفیف</th>
                <th scope="col">شناسه سبد</th>
                <th scope="col">مبلغ کل</th>
                <th scope="col">تاریخ ایجاد</th>
                <th scope="col">وضعیت پرداخت</th>
                <th scope="col">پرداخت کل</th>
                <th scope="col">کتاب های خریداری شده</th>
            </tr>
            </thead>
            <tbody>
            {% for factor in factors %}
                <tr>
                    <td class="editable">{{ factor.shipping_address.city }},{{ factor.shipping_address.address }}</td>
                    <td class="editable">{{ factor.discount }}</td>
                    <td class="editable">{{ factor.cart.id }}</td>
                    <td class="editable">{{ factor.price }}</td>
                    <td class="editable">{{ factor.created }}</td>
                    <td class="editable">{{ factor.payment }}</td>
                    <td class="editable">{{ factor.factor_total_price }}</td>
                    <td class="editable">
                        {% for cartitem in factor.item.all %}
                            <span>{{ cartitem.book.name }}</span><br>
                            <hr style="">
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock storeroom %}

SRC/templates/staff/orders.html
{% extends 'staff/staff.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
    <link rel="stylesheet" href="{% static 'css/storeroom.css' %}">
{% endblock %}
{% block title %}
    مشتریان
{% endblock %}
{% block storeroom %}
    <h2 class="card card-body text-center">مشتریان</h2>
    <div class="container card card-body storeroom">
        <table class="table table-hover text-right">
            <thead>
            <tr>
                <th scope="col">وضعیت سفارش</th>
                <th scope="col">تعداد</th>
                <th scope="col">شناسه سبد</th>
                <th scope="col">مبلغ کل</th>
                <th scope="col">نام کتاب</th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td class="editable">{{ order.get_ordered_display }}</td>
                    <td class="editable">{{ order.quantity }}</td>
                    <td class="editable">{{ order.cart.id }}</td>
                    <td class="editable">{{ order.total_price }} <span>تومان</span></td>
                    <td class="editable">{{ order.book}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock storeroom %}

SRC/templates/staff/report.html
{% extends 'staff/staff.html' %}
{% load static %}
{% block stylesheet %}

    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
    <link rel="stylesheet" href="{% static 'css/storeroom.css' %}">
{% endblock %}
{% block title %}
    انبار
{% endblock %}
{% block report %}
    <div class="container">
        <div class="container mt-3">
            <div class="row justify-content-center" style="height: 300px">
                <div style="background: #00AD7C" class="col-4">

                </div>
                <div style="background: #00AD7C" class="col-4"></div>
            </div>
            <br><br>
            <div class="row justify-content-center" style="height: 300px">
                <div style="background: #00AD7C" class="col-4">

                </div>
                <div style="background: #00AD7C" class="col-4"></div>
            </div>

        </div>
    </div>

{% endblock report %}

SRC/templates/staff/staff.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
    {#    <link rel="stylesheet" href="{% static 'css/staff_navbar.css' %}">#}
{% endblock %}
{% block title %}پنل کارمند{% endblock title %}
{% block content %}

    <nav class="navbar navbar-expand-lg navbar-dark staff-navbar ">


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" style="flex: inherit;" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       style="color: black"
                       aria-haspopup="true" aria-expanded="false">
                        تخفیف
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="{% url 'staff_add_cart_coupon' %}">سبد خرید</a>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="{% url 'staff_add_book_cache_coupon' %}">نقدی کتاب</a>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="{% url 'staff_add_book_percent_coupon' %}">درصدی کتاب</a>
                        <div class="dropdown-divider"></div>

                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       style="color: black"
                       aria-haspopup="true" aria-expanded="false">
                        کتاب
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="{% url 'staff_add_book' %}">افزودن کتاب</a>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="{% url 'staff_add_category' %}">افزودن دسته بندی</a>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="{% url 'storeroom' %}">انبار</a>
                        <div class="dropdown-divider"></div>

                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       style="color: black"
                       aria-haspopup="true" aria-expanded="false">
                        مشتریان
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                        <a class="dropdown-item" href="{% url 'orders_room' %}">سفارشات</a>
                        <div class="dropdown-divider"></div>
                        {##}
                        <a class="dropdown-item" href="{% url 'factors_room' %}">فاکتورها</a>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="{% url 'customers' %}">کاربران</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
                {#                <li class="nav-item active">#}
                {#                    <a style="color: black" class="nav-link" href="{% url 'report' %}" style="margin-left: -59px;">گزارش <span class="sr-only">(current)</span></a>#}
                {#                </li>#}

            </ul>

        </div>
    </nav>

    {#    {% block report %}#}
    {##}
    {#    {% endblock report %}#}
    {% block category %}

    {% endblock category %}
    {% block coupon %}
    {% endblock coupon %}
    {% block book %}

    {% endblock book %}
    {% block storeroom %}

    {% endblock storeroom %}
{% endblock content %}




SRC/templates/staff/storeroom.html
{% extends 'staff/staff.html' %}
{% load static %}
{% block stylesheet %}

    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
    <link rel="stylesheet" href="{% static 'css/storeroom.css' %}">
{% endblock %}
{% block title %}
    انبار
{% endblock %}
{% block storeroom %}
    <h2 class="card card-body text-center">انبار</h2>
    <div class="container">
        <div class="container mt-3">
            <div class="card card-body storeroom">
                <table class="table table-hover text-right">
                    <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">تاریخ ثبت</th>
                        <th scope="col">موجودی</th>
                        <th scope="col">قیمت</th>
                        <th scope="col">نویسنده</th>
                        <th scope="col">عنوان</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in book_storeroom %}
                        <tr>
                            <th scope="row">
                                <a href="{% url 'book_delete' book.slug %}" class="btn btn-danger">حذف</a>
                                <a href="{% url 'book_edit' book.slug %}" class="btn btn-warning">ویرایش</a>
                            </th>
                            <td class="editable">{{ book.created }}</td>
                            <td class="editable" >{{ book.stock }}</td>
                            <td class="editable" >{{ book.price }}</td>
                            <td class="editable" >{{ book.author }}</td>
                            <td class="editable" >{{ book.name }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock storeroom %}