SRC/BOOK_STORE/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf.urls.static import static
from BOOK_STORE import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^jet/', include('jet.urls', 'jet')),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('book.urls')),
    path('', include('coupon.urls')),
    path('', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SRC/book/urls.py
from django.urls import path
from book.views import AllBooksView, BookDetailView, CategoryBooksPageView, search_bar, \
    BookCreationView, CategoryCreationView, StoreroomView, BookEditView, BookDeleteView

urlpatterns = [
    path('search/', search_bar, name='search'),
    path('books', AllBooksView.as_view(), name='books'),
    path('book_details/<slug>', BookDetailView.as_view(), name='book_detail'),
    path('category_books/<slug>', CategoryBooksPageView.as_view(), name='category_books'),
    path('staff/add_book/', BookCreationView.as_view(), name='staff_add_book'),
    path('staff/add_category/', CategoryCreationView.as_view(), name='staff_add_category'),
    path('staff/storeroom/', StoreroomView.as_view(), name='storeroom'),
    path('staff/book/edit/<slug>', BookEditView.as_view(), name='book_edit'),
    path('staff/book/delete/<slug>', BookDeleteView.as_view(), name='book_delete'),
]

SRC/book/models.py
import datetime
import random
from django.db import models
from django.urls import reverse
from slugify import slugify


class Category(models.Model):
    """
    ایجاد یک کلاس برای ساخت جدولی از دسته بندی کتابها
    """

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    category = models.CharField(max_length=40, unique=True, verbose_name='دسته بندی')
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        """
        هنگام ذخیره ی هر شی اسلاگ آن را بررسی و بهتر می کند.
        """
        to_slug = self.slug
        if to_slug == "":
            to_slug = slugify(str(self.category) + " " + "category")
            qs = Category.objects.filter(slug=to_slug).exists()
            while qs:
                to_slug = slugify(to_slug + " " + str(random.randint(1, 500)))
                qs = Category.objects.filter(slug=to_slug).exists()
        self.slug = to_slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.category

    def get_absolute_url(self):
        return reverse('categorydetail', kwargs={'slug': self.slug})


class Book(models.Model):
    """
    برای ساخت جدولی برای ذخیره ی کالا یا همان کتاب
    """

    class Meta:
        ordering = ('-price',)
        verbose_name = 'کتاب'
        verbose_name_plural = 'کتاب ها'

    name = models.CharField(verbose_name='نام', max_length=50, unique=True)
    image = models.ImageField(verbose_name='تصویر', default='product.png', upload_to='books/')
    author = models.CharField(verbose_name='نویسنده', max_length=50)
    price = models.DecimalField(verbose_name='قیمت به تومان', max_digits=8, decimal_places=2)
    created = models.DateTimeField(verbose_name='تاریخ ثبت', auto_now_add=True)
    stock = models.IntegerField(verbose_name='موجودی', default=1)
    description = models.CharField(verbose_name='درباره کتاب', max_length=500, default='بدون توضیحات')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی')
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        """
        هنگام ذخیره ی هر شی اسلاگ آن را بررسی و بهتر می کند.
        """

        self.slug = slugify(self.name)
        book_slug = self.slug
        if book_slug == "":
            book_slug = slugify(str(self.name) + " " + "book")
            qs = Category.objects.filter(slug=book_slug).exists()
            while qs:
                book_slug = slugify(book_slug + " " + str(random.randint(1, 500)))
                qs = Category.objects.filter(slug=book_slug).exists()
        self.slug = book_slug
        super().save(*args, **kwargs)

    @property
    def total_price(self):
        """
        :return: قیمت نهایی هر کتاب پس از اعمال تمامی کد تخفیفهای درصدی و نقدی روی هر عنوان کتاب
        """

        total_cache_coupon = 0
        total_percent_coupon = 0

        cache_coupons_of_book_qs = self.bookcashcoupon_set.all()
        percent_coupons_of_book_qs = self.bookpercentcoupon_set.all()

        if cache_coupons_of_book_qs.exists():
            for cache_coupon in cache_coupons_of_book_qs:
                if cache_coupon.is_active:
                    now = datetime.datetime.now()
                    if (now > cache_coupon.valid_from.replace(tzinfo=None)) and (
                            now < cache_coupon.valid_to.replace(tzinfo=None)):
                        total_cache_coupon += cache_coupon.discount_price

        if percent_coupons_of_book_qs.exists():
            for percent_coupon in percent_coupons_of_book_qs:
                if percent_coupon.is_active:
                    now = datetime.datetime.now()
                    if (now > percent_coupon.valid_from.replace(tzinfo=None)) and (
                            now < percent_coupon.valid_to.replace(tzinfo=None)):
                        total_percent_coupon += percent_coupon.discount_percent

        self.price = float(self.price)
        self.price = int(self.price)
        book_total_price = ((self.price - total_cache_coupon) * (100 - total_percent_coupon)) / 100

        return book_total_price

    def __str__(self):
        return f'{self.name}'

    def no_change_price(self):
        if self.total_price == self.price:
            no_change = True
        else:
            no_change = False
        return no_change

    def get_absolute_url(self):
        return reverse('book_detail', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('add_cart', kwargs={'slug': self.slug})

SRC/book/forms.py
from django import forms
from book.models import Book, Category


class BookCreationForm(forms.ModelForm):
    """
    فرم ایجاد کتاب
    """

    class Meta:
        model = Book
        fields = ['name', 'author', 'price', 'stock', 'description', 'category', 'image']
        # fields = '__all__'

    description = forms.CharField(max_length=500, widget=forms.Textarea())
    use_required_attribute = ['name', 'author', 'price', 'stock', 'category', 'image']


class CategoryCreationForm(forms.ModelForm):
    """
    فرم ایجاد دسته بندی
    """

    class Meta:
        model = Category
        fields = ['category']

    use_required_attribute = ['category']

SRC/book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from book.forms import BookCreationForm, CategoryCreationForm
from book.models import Category, Book


class AllBooksView(ListView):
    """
    نمایش تمام کتاب ها در یک صفحه
    """

    model = Book
    template_name = 'book/all_books.html'
    context_object_name = 'books'


class CategoryBooksPageView(DetailView):
    """
    نمایش کتاب های یک دسته بندی
    """
    model = Category
    template_name = 'book/category_books.html'


class BookDetailView(DetailView):
    """
    نمایش جزئیات هر کتاب
    """

    model = Book
    template_name = 'book/book_details.html'


class BookCreationView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    ایجاد کتاب
    """

    form_class = BookCreationForm
    template_name = 'book/book_form.html'
    success_url = reverse_lazy('staff')
    permission_required = 'book.add_book'


class CategoryCreationView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    ایجاد دسته بندی
    """

    form_class = CategoryCreationForm
    template_name = 'book/category_form.html'
    success_url = reverse_lazy('staff')
    permission_required = 'book.add_category'


class StoreroomView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    انبار
    """

    model = Book
    context_object_name = 'book_storeroom'
    template_name = 'staff/storeroom.html'
    permission_required = 'book.view_book'


class BookEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    ویرایش کتاب
    """

    model = Book
    template_name = 'book/book_edit.html'
    fields = ['name', 'author', 'price', 'category', 'stock', 'description', 'image']
    success_url = reverse_lazy('storeroom')
    permission_required = 'book.change_book'


class BookDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """
    حذف کتاب
    """

    model = Book
    template_name = 'book/book_delete.html'
    success_url = reverse_lazy('storeroom')
    permission_required = 'book.delete_book'


def search_bar(request):
    """
    :param request: اسم یک کتاب یا یک نویسنده یا بخشی از آنها
    :return: لیستی از کناب هایی که نام یا نویسنده ی ان سرچ شده
    """

    if request.method == 'POST':
        searched = request.POST['searched']
        book_by_name = Book.objects.filter(name__contains=searched)
        book_by_author = Book.objects.filter(author__contains=searched)
        return render(request, 'book/search.html',
                      {'searched': searched, 'book_by_author': book_by_author, 'book_by_name': book_by_name})

    return render(request, 'book/search.html', {})

SRC/templates/book/all_books.html
{% extends '_base.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/books.css' %}">
{% endblock %}
{% block title %}
    کتاب ها
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for book in books %}
                <div class="col-xs-12 col-md-6 bootstrap snippets bootdeys">
                    <!-- product -->
                    <div class="product-content product-wrap clearfix text-right">
                        <div class="row">
                            <div class="col-md-5 col-sm-12 col-xs-12">
                                <div style="margin-right: 13px;">
                                    <img src="{{ book.image.url }}" alt="194x228"
                                         class="img-responsive image-product-home">
                                </div>
                            </div>
                            <div class="col-md-7 col-sm-12 col-xs-12">
                                <div class="product-deatil">
                                    <h5 class="name">
                                        <a href="#">
                                            {{ book.name }}
                                            {% for category in book.category.all %}
                                                <span>{{ category }}</span>
                                            {% endfor %}

                                        </a>
                                    </h5>
{#                                    {% if book.bookcashcoupon_set.all %}#}
{#                                        <del class="price-container" style="color: darkgray">#}
{#                                            <span>{{ book.price }}</span><span>هزارتومان</span>#}
{#                                        </del>#}
{#                                        <span class="tag1"></span>#}
{#                                        <p class="price-container" >#}
{#                                            <span>{{ book.total_price }}</span><span>هزارتومان</span>#}
{#                                        </p>#}
{#                                        <span class="tag1"></span>#}
{#                                    {% elif book.bookcashcoupon_set.all %}#}
{#                                        <del class="price-container" style="color: darkgray">#}
{#                                            <span>{{ book.price }}</span><span>هزارتومان</span>#}
{#                                        </del>#}
{#                                        <span class="tag1"></span>#}
{#                                        <p class="price-container" >#}
{#                                            <span>{{ book.total_price }}</span><span>هزارتومان</span>#}
{#                                        </p>#}
{#                                        <span class="tag1"></span>#}
{#                                    {% else %}#}
{#                                        <p class="price-container">#}
{#                                            <span>{{ book.price }}</span><span>هزارتومان</span>#}
{#                                        </p>#}
{#                                        <span class="tag1"></span>#}
{#                                    {% endif %}#}
                                {% if book.no_change_price %}
                                    <p class="price-container">
                                        <span>{{ book.price }}</span><span>هزارتومان</span>
                                    </p>
                                    <span class="tag1"></span>
                                {% elif not book.no_change_price %}
                                    <del class="price-container"
                                         style="color: darkgray">
                                        <span>{{ book.price }}</span><span>هزارتومان</span>
                                    </del>
                                    <span class="tag1"></span>
                                    <p class="price-container">
                                        <span>{{ book.total_price }}</span><span>هزارتومان</span>
                                    </p>
                                    <span class="tag1"></span>
                                {% endif %}
                                </div>
                                <br><br>
                                <div class="product-info smart-form">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <a href="{% url 'book_detail' book.slug %}" class="btn btn-success">مشاهده
                                            جزئیات</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    {#<a href="{% url 'bookdetail' book.slug %}" class="btn btn-primary">مشاهده جزئیات</a>#}
{% endblock content %}

SRC/templates/book/book_delete.html
{% extends 'staff/staff.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
{% endblock %}
{% block title %}حذف کتاب{% endblock title %}
{% block book %}
    <h2>حذف</h2>
    <h4>شما در حال حذف کتاب {{ book.name}} هستید !!</h4>
    <form method="post" class="form-control col-md-auto" accept-charset="utf-8" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">حذف</button>
    </form>

{% endblock book %}

SRC/templates/book/book_details.html
{% extends '_base.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/books.css' %}">
{% endblock %}
{% block title %}
    کتاب
{% endblock title %}
{% block content %}
    <!-- product -->
    <div class="mt-5">
        <div class="container">
            <div class="container">
                <div class="article-entry">
                    <div class="product-content product-wrap clearfix product-deatil">
                        <div class="row">
                            <div class="col-md-5 col-sm-12 col-xs-12">
                                <div class="product-image">
                                    <div class="item active">
                                        <img src="{{ object.image.url }}" class="img-responsive"
                                             style="width: 300px;height: 400px" alt=""/>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-md-offset-1 col-sm-12 col-xs-12 text-right">
                                <h2 class="name">
                                    {{ object.name }}
                                    <h5>نویسنده: <span>{{ object.author }}</span></h5>

                                </h2>
                                <hr/>
                                {#                                {% if book.bookcashcoupon_set.all %}#}
                                {#                                    <del class="price-container" style="color: darkgray">#}
                                {#                                        <span>{{ book.price }}</span><span>هزارتومان</span>#}
                                {#                                    </del>#}
                                {#                                    <span class="tag1"></span>#}
                                {#                                    <p class="price-container">#}
                                {#                                        <span>{{ book.total_price }}</span><span>هزارتومان</span>#}
                                {#                                    </p>#}
                                {#                                    <span class="tag1"></span>#}
                                {#                                {% elif book.bookcashcoupon_set.all %}#}
                                {#                                    <del class="price-container" style="color: darkgray">#}
                                {#                                        <span>{{ book.price }}</span><span>هزارتومان</span>#}
                                {#                                    </del>#}
                                {#                                    <span class="tag1"></span>#}
                                {#                                    <p class="price-container">#}
                                {#                                        <span>{{ book.total_price }}</span><span>هزارتومان</span>#}
                                {#                                    </p>#}
                                {#                                    <span class="tag1"></span>#}
                                {#                                {% else %}#}
                                {#                                    <p class="price-container">#}
                                {#                                        <span>{{ book.price }}</span><span>هزارتومان</span>#}
                                {#                                    </p>#}
                                {#                                    <span class="tag1"></span>#}
                                {#                                {% endif %}#}
                                {% if book.no_change_price %}
                                    <p class="price-container">
                                        <span>{{ book.price }}</span><span>هزارتومان</span>
                                    </p>
                                    <span class="tag1"></span>
                                {% elif not book.no_change_price %}
                                    <del class="price-container"
                                         style="color: darkgray">
                                        <span>{{ book.price }}</span><span>هزارتومان</span>
                                    </del>
                                    <span class="tag1"></span>
                                    <p class="price-container">
                                        <span>{{ book.total_price }}</span><span>هزارتومان</span>
                                    </p>
                                    <span class="tag1"></span>
                                {% endif %}
                                <hr/>
                                <div class="description description-tabs">
                                    <div id="myTabContent" class="tab-content">
                                        <div class="" id="more-information">
                                            <br/>
                                            <h3>درباره ی کتاب</h3>
                                            <p>
                                                {{ object.description }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <hr/>
                                <div class="row">
                                    <div class="col-sm-12 col-md-6 col-lg-6">
                                        {% if book.stock %}
                                            {% if user.is_authenticated %}
                                                <a href="{% url 'add_to_cart' book.slug %}"
                                                   class="btn btn-success btn-lg">افزودن به سبد
                                                    خرید
                                                </a>
                                            {% else %}
                                                <a href="{% url 'add_to_session' book.slug %}"
                                                   class="btn btn-success btn-lg">افزودن به سبد
                                                    خرید
                                                </a>
                                            {% endif %}
                                        {% else %}
                                            <h3>ناموجود</h3>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end product -->
{% endblock content %}

SRC/templates/book/book_edit.html
{% extends 'staff/staff.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
{% endblock %}
{% block title %}ویرایش کتاب{% endblock title %}
{% block book %}
    <div class="container mt-5">
        <div class="card card-body p-3">
            <div class="container mt-3 p-5">
                <h2 class="text-center">ویرایش</h2>
    <form class="text-right" method="post" class="form-control col-md-auto" accept-charset="utf-8" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="btn">ویرایش</button>
    </form>
            </div>
        </div>
    </div>

{% endblock book %}

SRC/templates/book/book_form.html
{% extends 'staff/staff.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
{% endblock %}
{% block title %}کتاب جدید{% endblock title %}
{% block book %}
    <div class="container mt-5">
        <div class="card card-body">
            <div class="container">
                <h2 class="text-center"> کتاب جدید</h2>
    <form class="text-right" method="post" class="form-control col-md-auto" accept-charset="utf-8" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="btn">ایجاد</button>
    </form>
            </div>
        </div>
    </div>

{% endblock book %}

SRC/templates/book/category_books.html
{% extends '_base.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/books.css' %}">
{% endblock %}
{% block title %}
    کتاب ها
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for book in object.book_set.all %}
                <div class="col-xs-12 col-md-6 bootstrap snippets bootdeys">
                    <!-- product -->
                    <div class="product-content product-wrap clearfix text-right">
                        <div class="row">
                            <div class="col-md-5 col-sm-12 col-xs-12">
                                <div style="margin-right: 13px;">
                                    <img src="{{ book.image.url }}" alt="194x228"
                                         class="img-responsive image-product-home">
                                </div>
                            </div>
                            <div class="col-md-7 col-sm-12 col-xs-12">
                                <div class="product-deatil">
                                    <h5 class="name">
                                        <a href="#">
                                            {{ book.name }}
                                            {% for category in book.category.all %}
                                                <span>{{ category }}</span>
                                            {% endfor %}

                                        </a>
                                    </h5>
                                    {#                                    <p class="price-container">#}
                                    {#                                        <span>{{ book.price }}</span><span>هزارتومان</span>#}
                                    {#                                    </p>#}
                                    {#                                    <span class="tag1"></span>#}
                                    {% if book.no_change_price %}
                                        <p class="price-container">
                                            <span>{{ book.price }}</span><span>هزارتومان</span>
                                        </p>
                                        <span class="tag1"></span>
                                    {% elif not book.no_change_price %}
                                        <del class="price-container"
                                             style="color: darkgray">
                                            <span>{{ book.price }}</span><span>هزارتومان</span>
                                        </del>
                                        <span class="tag1"></span>
                                        <p class="price-container">
                                            <span>{{ book.total_price }}</span><span>هزارتومان</span>
                                        </p>
                                        <span class="tag1"></span>
                                    {% endif %}
                                </div>
                                <br><br>
                                <div class="product-info smart-form">
                                    <div class="col-md-6 col-sm-6 col-xs-6">
                                        <a href="{% url 'book_detail' book.slug %}" class="btn btn-success">مشاهده
                                            جزئیات</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

SRC/templates/book/category_form.html
{% extends 'staff/staff.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/staff.css' %}">
{% endblock %}
{% block title %}دسته بندی جدید{% endblock title %}
{% block category %}
    <div class="container mt-5">
        <div class="card card-body p-2 mt-4">
            <h2 class="card card-header text-center">دسته بندی جدید</h2>
            <form class="text-right" method="post" class="form-control col-md-auto">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-warning">ایجاد</button>
            </form>

        </div>
    </div>
{% endblock category %}