SRC/BOOK_STORE/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf.urls.static import static
from BOOK_STORE import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^jet/', include('jet.urls', 'jet')),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('book.urls')),
    path('', include('coupon.urls')),
    path('', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SRC/book/urls.py
from django.urls import path
from book.views import AllBooksView, BookDetailView, CategoryBooksPageView, search_bar, \
    BookCreationView, CategoryCreationView, StoreroomView, BookEditView, BookDeleteView

urlpatterns = [
    path('search/', search_bar, name='search'),
    path('books', AllBooksView.as_view(), name='books'),
    path('book_details/<slug>', BookDetailView.as_view(), name='book_detail'),
    path('category_books/<slug>', CategoryBooksPageView.as_view(), name='category_books'),
    path('staff/add_book/', BookCreationView.as_view(), name='staff_add_book'),
    path('staff/add_category/', CategoryCreationView.as_view(), name='staff_add_category'),
    path('staff/storeroom/', StoreroomView.as_view(), name='storeroom'),
    path('staff/book/edit/<slug>', BookEditView.as_view(), name='book_edit'),
    path('staff/book/delete/<slug>', BookDeleteView.as_view(), name='book_delete'),
]

SRC/cart/urls.py
from django.urls import path
from cart.views import CartView, add_to_cart, remove_from_cart, quantity, quantity_next_cart, NextCartView, \
    add_to_next_cart, return_to_cart, remove_from_next_cart, create_factor, save_coupon_to_factor, success, \
    return_all_to_cart, HistoryListView, anonymous_cart, add_to_session, anonymous_cart_remove, FactorsView, \
    OrdersView, report

urlpatterns = [
    path('cart/', CartView.as_view(), name='cart'),
    path('anonymous_cart/', anonymous_cart, name='anonymous_cart'),
    path('next_cart/', NextCartView.as_view(), name='next_cart'),
    path('add_to_cart/<slug>', add_to_cart, name='add_to_cart'),
    path('add_to_next_cart/<slug>', add_to_next_cart, name='add_to_next_cart'),
    path('return_to_cart/<slug>', return_to_cart, name='return_to_cart'),
    path('return_all_to_cart/', return_all_to_cart, name='return_all_to_cart'),
    path('remove_from_cart/<slug>', remove_from_cart, name='cart_remove'),
    path('remove_from_next_cart/<slug>', remove_from_next_cart, name='remove_from_next_cart'),
    path('quantity/<slug>', quantity, name='quantity'),
    path('quantity_next_cart/<slug>', quantity_next_cart, name='quantity_next_cart'),
    path('payment/', create_factor, name='payment'),
    path('save_coupon_to_factor/', save_coupon_to_factor, name='save_coupon_to_factor'),
    path('success', success, name='success'),
    path('history', HistoryListView.as_view(), name='history'),
    path('add_to_session/<slug>', add_to_session, name='add_to_session'),
    path('anonymous_cart_remove/<slug>', anonymous_cart_remove, name='anonymous_cart_remove'),
    path('staff/factors/', FactorsView.as_view(), name='factors_room'),
    path('staff/oeders/', OrdersView.as_view(), name='orders_room'),
    path('staff/report/', report, name='report')
]

SRC/coupon/models.py
from django.db import models


class CartCoupon(models.Model):
    """
    کد تخفیف برای سبد خرید
    """

    class Meta:
        verbose_name = 'تخفیف درصدی سبد'
        verbose_name_plural = 'تخفیف درصدی سبدهای خرید'

    code = models.CharField(verbose_name='کد', max_length=30)
    valid_from = models.DateTimeField(verbose_name='تاریخ شروع')
    valid_to = models.DateTimeField(verbose_name='تاریخ انقضا')
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    discount_percent = models.IntegerField(verbose_name='درصد تخفیف', default=0)

    def __str__(self):
        return self.code


class BookCashCoupon(models.Model):
    """
    تخفیف نقدی کتاب. هر تخفیف می تواند روی چندین کتاب اعمال شود و هر کتاب می تواند چندین کد تخفیف داشته باشد.
    """

    class Meta:
        verbose_name = 'تخفیف نقدی کتاب'
        verbose_name_plural = 'تخفیف نقدی کتاب ها'

    valid_from = models.DateTimeField(verbose_name='تاریخ شروع')
    valid_to = models.DateTimeField(verbose_name='تاریخ انقضا')
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    discount_price = models.IntegerField(verbose_name='مبلغ تخفیف', default=0)
    books = models.ManyToManyField('book.Book', verbose_name='کتاب ها',  blank=True)

    def __str__(self):
        return f'{self.discount_price}'


class BookPercentCoupon(models.Model):
    """
    تخفیف درصدی کتاب. هر تخفیف می تواند روی چندین کتاب اعمال شود و هر کتاب می تواند چندین کد تخفیف داشته باشد.
    """

    class Meta:
        verbose_name = 'تخفیف درصدی کتاب'
        verbose_name_plural = 'تخفیف درصدی کتاب ها'

    valid_from = models.DateTimeField(verbose_name='تاریخ شروع')
    valid_to = models.DateTimeField(verbose_name='تاریخ انقضا')
    is_active = models.BooleanField(verbose_name='فعال', default=False)
    discount_percent = models.IntegerField(verbose_name='درصد تخفیف', default=0)
    books = models.ManyToManyField('book.Book', verbose_name='کتاب ها', blank=True)

    def __str__(self):
        return f'{self.discount_percent}'

SRC/cart/views.py
import datetime
import random
import string

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from account.models import ShippingAddress, CustomUser
from book.models import Book
from cart.models import CartItems, Cart, FinalizedOrders
from coupon.models import CartCoupon


class CartView(LoginRequiredMixin, ListView):
    """
    سبد خرید
    """

    model = Cart
    template_name = 'cart/cart.html'
    context_object_name = 'my_items'

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        :param object_list: -
        :param kwargs: -
        :return: قیمت نهایی فاکتور خرید
        """

        total_price_factor = 0
        for item in CartItems.objects.filter(cart=Cart.objects.get(user=self.request.user), ordered='O'):
            total_price_factor += item.total_price

        context = super().get_context_data(**kwargs)
        context['total_price_factor'] = total_price_factor
        context['addresses'] = ShippingAddress.objects.filter(user=self.request.user)
        return context

    def get_queryset(self):
        """
        :return: سفارشات درون سبد خرید کاربر
        """

        queryset = super(CartView, self).get_queryset()
        queryset = queryset.get(user=self.request.user).cartitems_set.filter(ordered='O')
        return queryset


class NextCartView(LoginRequiredMixin, ListView):
    """
    سبد خرید بعدی
    """

    model = Cart
    template_name = 'cart/next_cart.html'
    context_object_name = 'my_items'

    def get_queryset(self):
        """
        :return: سفارشات درون سبد خرید کاربر
        """

        queryset = super(NextCartView, self).get_queryset()
        queryset = queryset.get(user=self.request.user).cartitems_set.filter(ordered='U')
        return queryset


class HistoryListView(LoginRequiredMixin, ListView):
    """
    نمتایش خلاصه ای از تمام خرید های کاربر
    """

    model = FinalizedOrders
    template_name = 'cart/history.html'
    context_object_name = 'factors'

    def get_queryset(self):
        """
        :return: فاکتور خرید های کاربر
        """

        queryset = super(HistoryListView, self).get_queryset()
        queryset = queryset.filter(cart=Cart.objects.get(user=self.request.user))
        return queryset


class FactorsView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    تمام فاکتور خریدها در پنل کارمند
    """

    model = FinalizedOrders
    context_object_name = 'factors'
    template_name = 'staff/factors.html'
    queryset = FinalizedOrders.objects.all()
    permission_required = 'book.add_book'


class OrdersView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    تمام سفارشات در پنل کارمند
    """

    model = FinalizedOrders
    context_object_name = 'orders'
    template_name = 'staff/orders.html'
    queryset = CartItems.objects.all()
    permission_required = 'book.add_book'


@login_required()
def add_to_cart(request, slug):
    """
    :param request: 😐
    :param slug: اسلاگ کتاب انتخاب شده
    :return: سرجاش میمونه
    """

    book = get_object_or_404(Book, slug=slug)
    device = request.COOKIES['device']
    cart_qs = CartItems.objects.filter(book=book, ordered='O',
                                       cart=Cart.objects.get(user=request.user))
    if cart_qs.exists():
        cart_item = cart_qs[0]
        if cart_item.book.stock <= cart_item.quantity:
            pass
        else:
            cart_item.quantity += 1
            cart_item.save()
    else:
        cart_item = CartItems.objects.create(book=book, ordered='O', cart=Cart.objects.get(user=request.user))
        cart_item.save()

    return redirect('book_detail', slug=slug)


@login_required
def add_to_next_cart(request, slug):
    """
    آیتم انتخابی در سبد خرید را میگیرد و در لیست خرید بعدی قرار می دهد.
    :param request: -
    :param slug: -
    :return: صفحه ی لیست خرید
    """

    allowed = False
    book = get_object_or_404(Book, slug=slug)
    cart_qs = CartItems.objects.filter(book=book, ordered='O', cart=Cart.objects.get(user=request.user))
    if cart_qs.exists():
        cart_item = cart_qs[0]
        if cart_item.book.stock == 0:
            allowed = True
            cart_item.delete()
            return render(request, 'cart/cart.html', {'book': book, 'allowed': allowed})

        else:
            is_ordered_item_qs = CartItems.objects.filter(book=book, ordered='U',
                                                          cart=Cart.objects.get(user=request.user))
            if is_ordered_item_qs.exists():
                is_ordered_item = is_ordered_item_qs[0]
                is_ordered_item.quantity += cart_item.quantity
                is_ordered_item.save()
                cart_item.delete()
            else:
                cart_item.ordered = 'U'
                cart_item.save()

    return redirect('cart')


@login_required
def return_to_cart(request, slug):
    """
    :param request: 😐
    :param slug: اسلاگ کتاب انتخاب شده
    :return: سرجاش میمونه
    """

    book = get_object_or_404(Book, slug=slug)
    cart_qs = CartItems.objects.filter(book=book, ordered='U',
                                       cart=Cart.objects.get(user=request.user))

    if cart_qs.exists():
        cart_item = cart_qs[0]
        if cart_item.book.stock < cart_item.quantity:
            pass
        else:
            cart_item.ordered = 'O'
            cart_item.save()
    else:
        cart_item = CartItems.objects.create(book=book, ordered='O', cart=Cart.objects.get(user=request.user))
        cart_item.save()

    return redirect('next_cart')


@login_required()
def return_all_to_cart(request):
    """
    بازگردانی همه ی لیست خرید بعدی به سبد خرید
    :param request: -
    :return: -
    """

    next_cart_item = CartItems.objects.filter(ordered='U', cart=Cart.objects.get(user=request.user))
    if next_cart_item.exists():
        for item in next_cart_item:
            item.ordered = 'O'
            item.save()

    return redirect('next_cart')


@login_required()
def remove_from_cart(request, slug):
    """
    :param request: 😑
    :param slug: اسلاگ کتاب
    :return: سرجاش توی سبد خرید بمونه
    """

    book = get_object_or_404(Book, slug=slug)
    cart_qs = CartItems.objects.filter(book=book, cart=Cart.objects.get(user=request.user))
    if cart_qs.exists():
        cart_item = cart_qs[0]
        cart_item.delete()

    return redirect('cart')


@login_required()
def remove_from_next_cart(request, slug):
    """
    :param request: 😑
    :param slug: اسلاگ کتاب
    :return: سرجاش توی سبد خرید بعدی بمونه
    """

    book = get_object_or_404(Book, slug=slug)
    cart_qs = CartItems.objects.filter(book=book, cart=Cart.objects.get(user=request.user))
    if cart_qs.exists():
        cart_item = cart_qs[0]
        cart_item.delete()

    return redirect('next_cart')


@login_required()
def quantity(request, slug):
    """
    افزایش تعداد دلخواه از کتاب در سبد خرید به شرط داشتن موجودی کافی از کتاب کاهش تعداد دلخواه از کتاب در سبد خرید تا رسیدن به تعداد 1
    :param request: -
    :param slug: -
    :return: سرجاش میمونه
    """

    if request.method == 'POST' and 'plus_quantity' in request.POST:
        book = get_object_or_404(Book, slug=slug)
        cart_qs = CartItems.objects.filter(book=book, ordered='O', cart=Cart.objects.get(user=request.user))
        if cart_qs.exists():
            cart_item = cart_qs[0]
            if cart_item.quantity >= cart_item.book.stock:
                pass
            else:
                cart_item.quantity += 1
                cart_item.save()

    elif request.method == 'POST' and 'minus_quantity' in request.POST:
        book = get_object_or_404(Book, slug=slug)
        cart_qs = CartItems.objects.filter(book=book, ordered='O', cart=Cart.objects.get(user=request.user))
        if cart_qs.exists():
            cart_item = cart_qs[0]
            if cart_item.quantity <= 1:
                pass
            else:
                cart_item.quantity -= 1
                cart_item.save()

    return redirect('cart')


@login_required()
def quantity_next_cart(request, slug):
    """
    افزایش تعداد دلخواه از کتاب در سبد خرید به شرط داشتن موجودی کافی از کتاب کاهش تعداد دلخواه از کتاب در سبد خرید تا رسیدن به تعداد 1
    :param request: -
    :param slug: -
    :return: سرجاش میمونه
    """

    if request.method == 'POST' and 'plus_quantity' in request.POST:
        book = get_object_or_404(Book, slug=slug)
        cart_qs = CartItems.objects.filter(book=book, ordered='U', cart=Cart.objects.get(user=request.user))
        if cart_qs.exists():
            cart_item = cart_qs[0]
            if cart_item.quantity >= cart_item.book.stock:
                pass
            else:
                cart_item.quantity += 1
                cart_item.save()

    elif request.method == 'POST' and 'minus_quantity' in request.POST:
        book = get_object_or_404(Book, slug=slug)
        cart_qs = CartItems.objects.filter(book=book, ordered='U', cart=Cart.objects.get(user=request.user))
        if cart_qs.exists():
            cart_item = cart_qs[0]
            if cart_item.quantity <= 1:
                pass
            else:
                cart_item.quantity -= 1
                cart_item.save()

    return redirect('next_cart')


@login_required()
def create_factor(request):
    """
    ایجاد یک فاکتور خرید از سبد کاربر با ادرس
    :param request: -

SRC/templates/cart/anonymous_cart.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <link rel="stylesheet" href="{% static 'cart.css' %}">
{% endblock %}
{% block title %}سبد خرید من{% endblock title %}
{% block content %}
    <div class="row">
        <div class="container ">
            <div class="container mt-3">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'anonymous_cart' %}">سبد خرید</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'next_cart' %}">لیست خرید بعدی</a>
                    </li>

                </ul>
                <div class="card card-body storeroom">
                    <div class="container pb-5 mt-n2 mt-md-n3">
                        <div class="row">
                            <div class="col-xl-9 col-md-8">
                                <h2 style="background: #FFDFD3 !important;border-radius: 10px;"
                                    class="h6 d-flex flex-wrap justify-content-between align-items-center px-4 py-3 bg-secondary">
                                    <span>کتاب ها</span></h2>

                                {% if my_items %}


                                    {% for item in my_items %}
                                        <!-- Item-->
                                        <div class="d-sm-flex justify-content-between my-4 pb-4 border-bottom">
                                            <div class="media d-block d-sm-flex text-center text-sm-left">
                                                <div class="cart-item-thumb mx-auto mr-sm-4" href=""><img height="240px"
                                                                                                          width="200px"
                                                                                                          src="{{ item.image.url }}"
                                                                                                          alt="Product">
                                                </div>
                                                <div class="media-body pt-3 text-right pr-4">
                                                    <h3 class="product-card-title font-weight-semibold border-0 pb-0"><a
                                                            href="{% url 'book_detail' item.slug %}">{{ item.name }}</a>
                                                    </h3>
                                                    <div class="font-size-sm"><span
                                                            class="text-muted mr-2">نویسنده:</span>{{ item.author }}
                                                    </div>
                                                    {% if item.bookpercentcoupon_set.all %}
                                                        <div class="font-size-lg text-primary pt-2">
                                                            <del>{{ item.price }}</del>&nbsp;<span>تومان</span>
                                                        </div>
                                                        <div class="h4 text-primary pt-2">
                                                            <span>{{ item.total_price }}</span>&nbsp;<span>تومان</span>
                                                        </div>
                                                    {% elif item.bookcashcoupon_set.all %}
                                                        <div class="font-size-lg text-primary pt-2">
                                                            <del>{{ item.price }}</del>&nbsp;<span>تومان</span>
                                                        </div>
                                                        <div class="h4 text-primary pt-2">
                                                            <span>{{ item.total_price }}</span>&nbsp;<span>تومان</span>
                                                        </div>
                                                    {% else %}
                                                        <div class="h4 text-primary pt-2">
                                                            <span>{{ item.total_price }}</span>&nbsp;<span>تومان</span>
                                                        </div>

                                                    {% endif %}
                                                </div>
                                            </div>
                                            <form action="{% url 'quantity' item.slug %}" method="post">
                                                {% csrf_token %}
                                                <div class="pt-2 pt-sm-0 pl-sm-3 mx-auto mx-sm-0 text-center text-sm-left"
                                                     style="max-width: 10rem;">
                                                    <div class="form-group text-right mb-2">
                                                        <label for="quantity1">تعداد</label>
                                                        <div class="container">
                                                            <div class="row">
                                                                <div class="col-xs-3 col-xs-offset-3">
                                                                    <div class="input-group number-spinner">

                                                                        <button name="plus_quantity" type="submit"
                                                                                class="btn btn-default" data-dir="dwn">
                                                                            <i class="fas fa-plus"></i></button>
                                                                        <input readonly="readonly" type="text"
                                                                               class="form-control text-center"
                                                                               value="{{ item.quantity }}">
                                                                        <button name="minus_quantity" type="submit"
                                                                                class="btn btn-default" data-dir="up"><i
                                                                                class="fas fa-minus"></i></button>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <a href="{% url 'anonymous_cart_remove' item.slug %}"
                                                       class="btn btn-danger btn-sm btn-block mb-2">حذف</a>
{#                                                    <a href="{% url 'add_to_next_cart' item.book.slug %}"#}
{#                                                       class="btn btn-warning btn-sm btn-block mb-2"><p#}
{#                                                            style="font-size: 12px;padding-top: 11px">ذخیره درلیست خرید#}
{#                                                        بعدی</p></a>#}

                                                </div>
                                            </form>
                                        </div>
                                    {% endfor %}
                                {% elif not my_items %}
                                    <div class=""><img height = "-moz-available;" src="{% static 'images/empty-cart.png' %}" alt=""></div>
                                {% endif %}


                            </div>
                            <!-- Sidebar-->
                            <div class="col-xl-3 col-md-4 pt-3 pt-md-0">

                                    <h2 style="background: #D291BC !important;border-radius: 10px;  "
                                        class="h6 px-4 py-3 bg-secondary text-center">، برای تجربه ی بهتر لطفا ابتدا وارد شوید.
                                    </h2>
                                    <a href="{% url 'login' %}" class="btn btn-warning btn-block" type="submit" style="margin-top: 15px">
                                            ورود
                                    </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


SRC/templates/cart/history.html
{% extends '_base.html' %}
{% load static %}
{% block stylesheet %}

    <link rel="stylesheet" href="{% static 'css/storeroom.css' %}">
{% endblock %}
{% block title %}
    فاکتور های من
{% endblock %}
{% block content %}
    <h2 class="card card-body text-center">فاکتورهای من</h2>
    <div class="container">
        <div class="container mt-3">
            <div class="card card-body storeroom">
                <table class="table table-hover text-right">
                    <thead style="background: #957DAD">
                    <tr>

                        <th scope="col"> آدرس تحویل</th>
                        <th scope="col">تخفیف سبد خرید</th>
                        <th scope="col">مبلغ پرداخت شده</th>
                        <th scope="col">تاریخ</th>
                        <th scope="col">عنوان ککتاب ها</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for factor in factors %}
                        <tr>
                            <td class="editable">{{ factor.shipping_address.city }}،{{ factor.shipping_address.address}}</td>
                            <td class="editable" >{{ factor.discount }}<span>درصد</span></td>
                            <td class="editable" >{{ factor.factor_total_price }}<span>تومان</span></td>
                            <td class="editable" >{{ factor.created}}</td>
                            <td>
                                {% for item  in factor.item.all  %}
                                    <span>{{ item.book.name }}</span><br>
                                    <hr>
                                {% endfor %}

                            </td>
                            </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

SRC/templates/cart/payment.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/payment.css' %}">
    <title>پرداخت</title>
</head>
<body>
<div class="container mt-5">
    <div class="card card-body mt-5">
        <div class="container">
            <form action="{% url 'save_coupon_to_factor' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ finalized_obj.id }}" name="finalized_obj_id">
                <label class="col-4" for="1213">قیمت کل:</label><br>
                <div class="card" style="background: cadetblue">
                    <input id="1213" class="form-control-plaintext text-center" type="text"
                           readonly="readonly"
                           value="{{ finalized_obj.factor_total_price }}">
                </div>
                <hr>
                <label for="coupon123">کد تخفیف را اینجا وارد کنید</label><br>
                <input class="col-2 p-2" type="text" name="coupon" id="coupon123"><br><br>
                <button style="padding-bottom: 6px !important;" class="btn btn-success p-2 col-2" type="submit">اعمال کد تخفیف
                </button>
            </form>
            <hr>
            <form action="{%  url 'success' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ finalized_obj.id }}" name="finalized_obj_id">
                <button class="btn btn-danger p-2 col-2" type="submit">پرداخت</button>
            </form>
        </div>
    </div>
    <br>
    <a class="btn btn-primary  col-2" href="{% url 'cart' %}">بازگشت به سبد خرید</a>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>
